name: nebux_design_system
description: "A comprehensive Flutter design system package that provides consistent theming, typography, spacing, and UI components for Nebux applications."
homepage: https://github.com/joicodev/nebux_design_system
repository: https://github.com/joicodev/nebux_design_system
issue_tracker: https://github.com/joicodev/nebux_design_system/issues
version: 1.0.1

environment:
  sdk: ^3.9.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.1
  toml: ^0.18.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  # font_awesome_flutter: ^10.8.0
  double_back_to_exit: ^1.2.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  collection: ^1.18.0
  flutter_skeleton_ui: ^0.0.6
  app_shimmer: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/translations/

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
